#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1

traits:
    - securedBySteroidsApiKey:
        headers:
          steroidsApiKey:
            type: string
            example: exampleapikey
            default: 37b1f3705d4564280f825ffb654e3d5ba81d4fc9f49b91ce5473f037f86fe454
          steroidsAppId:
            type: integer
            example: 1234
            default: 80252
  
schemas:
  - Event_collection: '{"$schema":"http://json-schema.org/schema","title":"Event collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Event representation","properties":{"Food":{"type":"string"},"Who":{"type":"string"},"Date":{"type":"string"},"Location":{"type":"string"},"Organization":{"type":"string"},"Website":{"type":"string"},"StartTime":{"type":"string"},"EndTime":{"type":"string"},"Description":{"type":"string"},"Address":{"type":"string"},"Room":{"type":"string"}},"required":[]}}}}'
  - Event_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Event representation","properties":{"object":{"type":"object","properties":{"Food":{"type":"string"},"Who":{"type":"string"},"Date":{"type":"string"},"Location":{"type":"string"},"Organization":{"type":"string"},"Website":{"type":"string"},"StartTime":{"type":"string"},"EndTime":{"type":"string"},"Description":{"type":"string"},"Address":{"type":"string"},"Room":{"type":"string"}},"required":[]}}}'
  - Events_collection: '{"$schema":"http://json-schema.org/schema","title":"Events collection","type":"object","properties":{"results":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Events representation","properties":{"Date":{"type":"object"},"Food":{"type":"string"},"Location":{"type":"string"},"Organization":{"type":"string"},"Time":{"type":"object"},"Who":{"type":"string"},"createdAt":{"type":"string"},"objectId":{"type":"string"},"updatedAt":{"type":"string"}},"required":[]}}}}'
  - Events_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Events representation","properties":{"Date":{"type":"object"},"Food":{"type":"string"},"Location":{"type":"string"},"Organization":{"type":"string"},"Time":{"type":"object"},"Who":{"type":"string"},"createdAt":{"type":"string"},"objectId":{"type":"string"},"updatedAt":{"type":"string"}},"required":[]}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:

  - parse_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "results"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - parse_member:
      usage: This resourceType should be used for any parse item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/Event:
  description: |
    {
      "resourceName": "Event",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member

/Events:
  description: |
    {
      "resourceName": "Events",
      "identifierKey": "objectId"
    }
  type: parse_collection
  /{id}:
    type: parse_member





